version: "3"
services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc
    env_file: .env
    restart: always
    volumes:
      - /data/minecraft:/data
    ports:
      - "25565:25565"